#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "ghdark"
    colorscheme_bg = "dark"
    statusline_color_scheme = "blue"
    custom_color_palette = [
      ['#282C34', '#98C379', 114, 235],
      ['#ABB2BF', '#3E4452', 236, 144],
      ['#ABB2BF', '#3B4048', 238, 144],
      ['#5C6370', 59],
      ['#282c34', '#00af87', 235, 36],
      ['#282c34', '#ff8700', 235, 208],
      ['#282c34', '#af5f5f', 235, 131],
      ['#282828', '#689d6a', 235, 72],
      ['#282828', '#8f3f71', 235, 132],
    ]

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    enable_statusline_mode = true
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    windows_smartclose = ''

[[custom_plugins]]
    repo = "wojciechkepka/vim-github-dark"
    merged = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30


[[layers]]
name = "core#statusline"
